apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: salhianis20/backend  # Update with your backend image
        ports:
        - containerPort: 5050
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/mydatabase"  # MongoDB connection URI
        readinessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 10
