apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-app-ingress
spec:
  rules:
    - host: mern-app.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 5173
